---
apiVersion: v1
kind: pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    author: Deepika
spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_resultapp
      ports:
        - containerPort: 80
...
