---
apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    name: worker-pod
    author: Deepika
spec:
  containers:
    - name: worker-app
      image: dockersamples/examplevotingapp_worker
...